subroutine axial_and_shear(nFull, d_full, t_full, z_full, Fx, Fy, Fz, qx, qy, &
    & Mxx, Myy, rho, mrhox, m, axial_stress, shear_stress)

    implicit none

    ! define precision to be the standard for a double precision ! on local system
    integer, parameter :: dp = kind(0.d0)

    ! in
    integer, intent(in) :: nFull
    real(dp), intent(in) :: Fx, Fy, Fz, Mxx, Myy
    real(dp), dimension(nFull), intent(in) :: d_full, t_full, z_full, qx, qy, rho
    real(dp), intent(in) :: m, mrhox !should change this in the future to allow more inputs

    !out
    real(dp), dimension(nFull), intent(out) :: axial_stress, shear_stress

    !local
    integer :: i, j
    real(dp) :: g, massAbove, Fxtop, qx_top, qx_bot, qy_top, qy_bot, z_top, z_bot, &
        & qxload, qyload, Q_x, Q_y, qxmom, qymom, area, volume, sectionMass, pi, Myy_w_g, Fz_w_g
    real(dp), dimension(nFull) :: Az, F_X, F_Y, F_Z, MX, MY, Iyy

    pi = 3.1415926_dp
    g = 9.81_dp
    Fz_w_g = Fz - m*g !add load from gravity of extra mass
    Myy_w_g = Myy + m*g*mrhox !add moment from gravity of extra mass
    massAbove = 0.0_dp

    F_X(nFull) = -Fx
    F_Y(nFull) = -Fy
    F_Z(nFull) = Fz_w_g
    MX(nFull) = Mxx
    MY(nFull) = Myy_w_g

    do i = nFull-1,1,-1

        Fxtop = F_X(i+1)
        qx_top = qx(i+1)
        qx_bot = qx(i)
        qy_top = qy(i+1)
        qy_bot = qy(i)
        z_top = z_full(i+1)
        z_bot = z_full(i)

        qxload = qx_bot*(z_top-z_bot)+(qx_top-qx_bot)/(z_top-z_bot)*(0.5_dp*(z_top**2_dp-z_bot**2_dp)-z_bot*(z_top-z_bot))
        qyload = qy_bot*(z_top-z_bot)+(qy_top-qy_bot)/(z_top-z_bot)*(0.5_dp*(z_top**2_dp-z_bot**2_dp)-z_bot*(z_top-z_bot))

        Q_x = (qx_top-qx_bot)/(z_top-z_bot)
        Q_y = (qy_top-qy_bot)/(z_top-z_bot)
        qxmom = Q_y*1._dp/3._dp*(z_top**3_dp-z_bot**3_dp)+(qy_bot-2._dp*Q_y*z_bot)*0.5_dp*&
                &(z_top**2_dp-z_bot**2_dp)+(Q_y*z_bot**2_dp-qy_bot*z_bot)*(z_top-z_bot)
        qymom = Q_x*1._dp/3._dp*(z_top**3_dp-z_bot**3_dp)+(qx_bot-2._dp*Q_x*z_bot)*0.5_dp*&
                &(z_top**2_dp-z_bot**2_dp)+(Q_x*z_bot**2_dp-qx_bot*z_bot)*(z_top-z_bot)

        F_X(i) = F_X(i+1)-qxload
        F_Y(i) = F_Y(i+1)-qyload
        MX(i) = MX(i+1)+qxmom-(F_Y(i+1)*(z_top-z_bot))
        MY(i) = MY(i+1)+qymom-(F_X(i+1)*(z_top-z_bot))

        !Extra force from mass of tower
        area = (d_full(i+1)+d_full(i))/2._dp*pi*(t_full(i+1)+t_full(i))/2._dp
        volume = area*(z_full(i+1)-z_full(i))
        sectionMass = volume*rho(i)
        massAbove = massAbove + sectionMass
        F_Z(i) = Fz_w_g - massAbove*g


    end do


    Az = pi*d_full*t_full
    Iyy = pi*(d_full/2._dp)**3_dp*t_full
    axial_stress = F_Z/Az - sqrt(MX**2_dp+MY**2_dp)/Iyy*d_full/2.0_dp
    shear_stress = 2._dp*sqrt(F_X**2_dp+F_Y**2_dp)/Az

end subroutine axial_and_shear



!
!
!
!
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of axial_and_shear in forward (tangent) mode:
!   variations   of useful results: axial_stress shear_stress
!   with respect to varying inputs: qx qy d_full t_full z_full
!   RW status of diff variables: axial_stress:out qx:in qy:in shear_stress:out
!                d_full:in t_full:in z_full:in
! SUBROUTINE AXIAL_AND_SHEAR_DV(nfull, d_full, d_fulld, t_full, t_fulld, &
! & z_full, z_fulld, fx, fy, fz, qx, qxd, qy, qyd, mxx, myy, rho, mrhox, m&
! & , axial_stress, axial_stressd, shear_stress, shear_stressd, nbdirs)
!   ! USE DIFFSIZES
! !  Hint: nbdirs should be the maximum number of differentiation directions
!   IMPLICIT NONE
! ! define precision to be the standard for a double precision ! on local system
!   INTEGER, PARAMETER :: dp=KIND(0.d0)
! ! in
!   INTEGER, INTENT(IN) :: nfull
!   REAL(dp), INTENT(IN) :: fx, fy, fz, mxx, myy
!   REAL(dp), DIMENSION(nfull), INTENT(IN) :: d_full, t_full, z_full, qx, &
! & qy, rho
!   REAL(dp), DIMENSION(nbdirs, nfull), INTENT(IN) :: d_fulld, t_fulld&
! & , z_fulld, qxd, qyd
! !should change this in the future to allow more inputs
!   REAL(dp), INTENT(IN) :: m, mrhox
! !out
!   REAL(dp), DIMENSION(nfull), INTENT(OUT) :: axial_stress, shear_stress
!   REAL(dp), DIMENSION(nbdirs, nfull), INTENT(OUT) :: axial_stressd, &
! & shear_stressd
! !local
!   INTEGER :: i, j
!   REAL(dp) :: g, massabove, fxtop, qx_top, qx_bot, qy_top, qy_bot, z_top&
! & , z_bot, qxload, qyload, q_x, q_y, qxmom, qymom, area, volume, &
! & sectionmass, pi, myy_w_g, fz_w_g
!   REAL(dp), DIMENSION(nbdirs) :: massaboved, qx_topd, qx_botd, &
! & qy_topd, qy_botd, z_topd, z_botd, qxloadd, qyloadd, q_xd, q_yd, qxmomd&
! & , qymomd, aread, volumed, sectionmassd
!   REAL(dp), DIMENSION(nfull) :: az, f_x, f_y, f_z, mx, my, iyy
!   REAL(dp), DIMENSION(nbdirs, nfull) :: azd, f_xd, f_yd, f_zd, mxd, &
! & myd, iyyd
!   INTRINSIC KIND
!   INTRINSIC SQRT
!   REAL(dp), DIMENSION(nfull) :: arg1
!   REAL(dp), DIMENSION(nbdirs, nfull) :: arg1d
!   REAL(dp), DIMENSION(nfull) :: result1
!   REAL(dp), DIMENSION(nbdirs, nfull) :: result1d
!   INTEGER :: nd
!   INTEGER :: nbdirs
!   pi = 3.1415926_dp
!   g = 9.81_dp
! !add load from gravity of extra mass
!   fz_w_g = fz - m*g
! !add moment from gravity of extra mass
!   myy_w_g = myy + m*g*mrhox
!   massabove = 0.0_dp
!   f_x(nfull) = -fx
!   f_y(nfull) = -fy
!   f_z(nfull) = fz_w_g
!   mx(nfull) = mxx
!   my(nfull) = myy_w_g
!   DO nd=1,nbdirs
!     myd(nd, :) = 0.0
!     massaboved(nd) = 0.0
!     f_xd(nd, :) = 0.0
!     f_yd(nd, :) = 0.0
!     f_zd(nd, :) = 0.0
!     mxd(nd, :) = 0.0
!   END DO
!   DO i=nfull-1,1,-1
!     fxtop = f_x(i+1)
!     qx_top = qx(i+1)
!     qx_bot = qx(i)
!     qy_top = qy(i+1)
!     qy_bot = qy(i)
!     z_top = z_full(i+1)
!     z_bot = z_full(i)
!     qxload = qx_bot*(z_top-z_bot) + (qx_top-qx_bot)/(z_top-z_bot)*(&
! &     0.5_dp*(z_top**2_dp-z_bot**2_dp)-z_bot*(z_top-z_bot))
!     qyload = qy_bot*(z_top-z_bot) + (qy_top-qy_bot)/(z_top-z_bot)*(&
! &     0.5_dp*(z_top**2_dp-z_bot**2_dp)-z_bot*(z_top-z_bot))
!     q_x = (qx_top-qx_bot)/(z_top-z_bot)
!     q_y = (qy_top-qy_bot)/(z_top-z_bot)
!     f_x(i) = f_x(i+1) - qxload
!     f_y(i) = f_y(i+1) - qyload
!     area = (d_full(i+1)+d_full(i))/2._dp*pi*(t_full(i+1)+t_full(i))/&
! &     2._dp
!     DO nd=1,nbdirs
!       qx_topd(nd) = qxd(nd, i+1)
!       qx_botd(nd) = qxd(nd, i)
!       qy_topd(nd) = qyd(nd, i+1)
!       qy_botd(nd) = qyd(nd, i)
!       z_topd(nd) = z_fulld(nd, i+1)
!       z_botd(nd) = z_fulld(nd, i)
!       qxloadd(nd) = qx_botd(nd)*(z_top-z_bot) + qx_bot*(z_topd(nd)-&
! &       z_botd(nd)) + ((qx_topd(nd)-qx_botd(nd))*(z_top-z_bot)-(qx_top-&
! &       qx_bot)*(z_topd(nd)-z_botd(nd)))*(0.5_dp*(z_top**2_dp-z_bot**&
! &       2_dp)-z_bot*(z_top-z_bot))/(z_top-z_bot)**2 + (qx_top-qx_bot)*(&
! &       0.5_dp*(2_dp*z_top*z_topd(nd)-2_dp*z_bot*z_botd(nd))-z_botd(nd)*&
! &       (z_top-z_bot)-z_bot*(z_topd(nd)-z_botd(nd)))/(z_top-z_bot)
!       qyloadd(nd) = qy_botd(nd)*(z_top-z_bot) + qy_bot*(z_topd(nd)-&
! &       z_botd(nd)) + ((qy_topd(nd)-qy_botd(nd))*(z_top-z_bot)-(qy_top-&
! &       qy_bot)*(z_topd(nd)-z_botd(nd)))*(0.5_dp*(z_top**2_dp-z_bot**&
! &       2_dp)-z_bot*(z_top-z_bot))/(z_top-z_bot)**2 + (qy_top-qy_bot)*(&
! &       0.5_dp*(2_dp*z_top*z_topd(nd)-2_dp*z_bot*z_botd(nd))-z_botd(nd)*&
! &       (z_top-z_bot)-z_bot*(z_topd(nd)-z_botd(nd)))/(z_top-z_bot)
!       q_xd(nd) = ((qx_topd(nd)-qx_botd(nd))*(z_top-z_bot)-(qx_top-qx_bot&
! &       )*(z_topd(nd)-z_botd(nd)))/(z_top-z_bot)**2
!       q_yd(nd) = ((qy_topd(nd)-qy_botd(nd))*(z_top-z_bot)-(qy_top-qy_bot&
! &       )*(z_topd(nd)-z_botd(nd)))/(z_top-z_bot)**2
!       qxmomd(nd) = q_yd(nd)*(z_top**3_dp-z_bot**3_dp)/3._dp + q_y*(3_dp*&
! &       z_top**2.0*z_topd(nd)-3_dp*z_bot**2.0*z_botd(nd))/3._dp + 0.5_dp&
! &       *((qy_botd(nd)-2._dp*(q_yd(nd)*z_bot+q_y*z_botd(nd)))*(z_top**&
! &       2_dp-z_bot**2_dp)+(qy_bot-2._dp*q_y*z_bot)*(2_dp*z_top*z_topd(nd&
! &       )-2_dp*z_bot*z_botd(nd))) + (q_yd(nd)*z_bot**2_dp+q_y*2_dp*z_bot&
! &       *z_botd(nd)-qy_botd(nd)*z_bot-qy_bot*z_botd(nd))*(z_top-z_bot) +&
! &       (q_y*z_bot**2_dp-qy_bot*z_bot)*(z_topd(nd)-z_botd(nd))
!       qymomd(nd) = q_xd(nd)*(z_top**3_dp-z_bot**3_dp)/3._dp + q_x*(3_dp*&
! &       z_top**2.0*z_topd(nd)-3_dp*z_bot**2.0*z_botd(nd))/3._dp + 0.5_dp&
! &       *((qx_botd(nd)-2._dp*(q_xd(nd)*z_bot+q_x*z_botd(nd)))*(z_top**&
! &       2_dp-z_bot**2_dp)+(qx_bot-2._dp*q_x*z_bot)*(2_dp*z_top*z_topd(nd&
! &       )-2_dp*z_bot*z_botd(nd))) + (q_xd(nd)*z_bot**2_dp+q_x*2_dp*z_bot&
! &       *z_botd(nd)-qx_botd(nd)*z_bot-qx_bot*z_botd(nd))*(z_top-z_bot) +&
! &       (q_x*z_bot**2_dp-qx_bot*z_bot)*(z_topd(nd)-z_botd(nd))
!       f_xd(nd, i) = f_xd(nd, i+1) - qxloadd(nd)
!       f_yd(nd, i) = f_yd(nd, i+1) - qyloadd(nd)
!       mxd(nd, i) = mxd(nd, i+1) + qxmomd(nd) - f_yd(nd, i+1)*(z_top-&
! &       z_bot) - f_y(i+1)*(z_topd(nd)-z_botd(nd))
!       myd(nd, i) = myd(nd, i+1) + qymomd(nd) - f_xd(nd, i+1)*(z_top-&
! &       z_bot) - f_x(i+1)*(z_topd(nd)-z_botd(nd))
! !Extra force from mass of tower
!       aread(nd) = pi*((d_fulld(nd, i+1)+d_fulld(nd, i))*(t_full(i+1)+&
! &       t_full(i))/2._dp+(d_full(i+1)+d_full(i))*(t_fulld(nd, i+1)+&
! &       t_fulld(nd, i))/2._dp)/2._dp
!       volumed(nd) = aread(nd)*(z_full(i+1)-z_full(i)) + area*(z_fulld(nd&
! &       , i+1)-z_fulld(nd, i))
!       sectionmassd(nd) = rho(i)*volumed(nd)
!       massaboved(nd) = massaboved(nd) + sectionmassd(nd)
!       f_zd(nd, i) = -(g*massaboved(nd))
!     END DO
!     qxmom = q_y*1._dp/3._dp*(z_top**3_dp-z_bot**3_dp) + (qy_bot-2._dp*&
! &     q_y*z_bot)*0.5_dp*(z_top**2_dp-z_bot**2_dp) + (q_y*z_bot**2_dp-&
! &     qy_bot*z_bot)*(z_top-z_bot)
!     qymom = q_x*1._dp/3._dp*(z_top**3_dp-z_bot**3_dp) + (qx_bot-2._dp*&
! &     q_x*z_bot)*0.5_dp*(z_top**2_dp-z_bot**2_dp) + (q_x*z_bot**2_dp-&
! &     qx_bot*z_bot)*(z_top-z_bot)
!     mx(i) = mx(i+1) + qxmom - f_y(i+1)*(z_top-z_bot)
!     my(i) = my(i+1) + qymom - f_x(i+1)*(z_top-z_bot)
!     volume = area*(z_full(i+1)-z_full(i))
!     sectionmass = volume*rho(i)
!     massabove = massabove + sectionmass
!     f_z(i) = fz_w_g - massabove*g
!   END DO
!   az = pi*d_full*t_full
!   iyy = pi*(d_full/2._dp)**3_dp*t_full
!   arg1(:) = mx**2_dp + my**2_dp
!   result1 = SQRT(arg1(:))
!   DO nd=1,nbdirs
!     azd(nd, :) = pi*(d_fulld(nd, :)*t_full+d_full*t_fulld(nd, :))
!     iyyd(nd, :) = pi*(3_dp*(d_full/2._dp)**2.0*d_fulld(nd, :)*t_full/&
! &     2._dp+(d_full/2._dp)**3_dp*t_fulld(nd, :))
!     arg1d(nd, :) = 2_dp*mx*mxd(nd, :) + 2_dp*my*myd(nd, :)
!     WHERE (arg1(:) .EQ. 0.0)
!       result1d(nd, :) = 0.0
!     ELSEWHERE
!       result1d(nd, :) = arg1d(nd, :)/(2.0*SQRT(arg1(:)))
!     END WHERE
!     axial_stressd(nd, :) = (f_zd(nd, :)*az-f_z*azd(nd, :))/az**2 - ((&
! &     result1d(nd, :)*iyy-result1*iyyd(nd, :))*d_full/iyy**2+result1*&
! &     d_fulld(nd, :)/iyy)/2.0_dp
!     arg1d(nd, :) = 2_dp*f_x*f_xd(nd, :) + 2_dp*f_y*f_yd(nd, :)
!   END DO
!   axial_stress = f_z/az - result1/iyy*d_full/2.0_dp
!   arg1(:) = f_x**2_dp + f_y**2_dp
!   result1 = SQRT(arg1(:))
!   DO nd=1,nbdirs
!     WHERE (arg1(:) .EQ. 0.0)
!       result1d(nd, :) = 0.0
!     ELSEWHERE
!       result1d(nd, :) = arg1d(nd, :)/(2.0*SQRT(arg1(:)))
!     END WHERE
!     shear_stressd(nd, :) = (2._dp*result1d(nd, :)*az-2._dp*result1*azd(&
! &     nd, :))/az**2
!   END DO
!   shear_stress = 2._dp*result1/az
! END SUBROUTINE AXIAL_AND_SHEAR_DV


!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of axial_and_shear in reverse (adjoint) mode:
!   gradient     of useful results: axial_stress shear_stress
!   with respect to varying inputs: axial_stress m myy qx qy shear_stress
!                d_full fx fy fz mxx t_full z_full
!   RW status of diff variables: axial_stress:in-zero m:out myy:out
!                qx:out qy:out shear_stress:in-zero d_full:out
!                fx:out fy:out fz:out mxx:out t_full:out z_full:out
!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:54
!
!  Differentiation of axial_and_shear in forward (tangent) mode:
!   variations   of useful results: axial_stress shear_stress
!   with respect to varying inputs: m myy qx qy d_full fx fy fz
!                mxx t_full z_full
!   RW status of diff variables: axial_stress:out m:in myy:in qx:in
!                qy:in shear_stress:out d_full:in fx:in fy:in fz:in
!                mxx:in t_full:in z_full:in
SUBROUTINE AXIAL_AND_SHEAR_DV(nfull, d_full, d_fulld, t_full, t_fulld, &
& z_full, z_fulld, fx, fxd, fy, fyd, fz, fzd, qx, qxd, qy, qyd, mxx, &
& mxxd, myy, myyd, rho, mrhox, m, md, axial_stress, axial_stressd, &
& shear_stress, shear_stressd, nbdirs)
  ! USE DIFFSIZES
!  Hint: nbdirs should be the maximum number of differentiation directions
  IMPLICIT NONE
! define precision to be the standard for a double precision ! on local system
  INTEGER, PARAMETER :: dp=KIND(0.d0)
! in
  INTEGER, INTENT(IN) :: nfull
  REAL(dp), INTENT(IN) :: fx, fy, fz, mxx, myy
  REAL(dp), DIMENSION(nbdirs), INTENT(IN) :: fxd, fyd, fzd, mxxd, &
& myyd
  REAL(dp), DIMENSION(nfull), INTENT(IN) :: d_full, t_full, z_full, qx, &
& qy, rho
  REAL(dp), DIMENSION(nbdirs, nfull), INTENT(IN) :: d_fulld, t_fulld&
& , z_fulld, qxd, qyd
!should change this in the future to allow more inputs
  REAL(dp), INTENT(IN) :: m, mrhox
  REAL(dp), DIMENSION(nbdirs), INTENT(IN) :: md
!out
  REAL(dp), DIMENSION(nfull), INTENT(OUT) :: axial_stress, shear_stress
  REAL(dp), DIMENSION(nbdirs, nfull), INTENT(OUT) :: axial_stressd, &
& shear_stressd
!local
  INTEGER :: i, j
  REAL(dp) :: g, massabove, fxtop, qx_top, qx_bot, qy_top, qy_bot, z_top&
& , z_bot, qxload, qyload, q_x, q_y, qxmom, qymom, area, volume, &
& sectionmass, pi, myy_w_g, fz_w_g
  REAL(dp), DIMENSION(nbdirs) :: massaboved, qx_topd, qx_botd, &
& qy_topd, qy_botd, z_topd, z_botd, qxloadd, qyloadd, q_xd, q_yd, qxmomd&
& , qymomd, aread, volumed, sectionmassd, myy_w_gd, fz_w_gd
  REAL(dp), DIMENSION(nfull) :: az, f_x, f_y, f_z, mx, my, iyy
  REAL(dp), DIMENSION(nbdirs, nfull) :: azd, f_xd, f_yd, f_zd, mxd, &
& myd, iyyd
  INTRINSIC KIND
  INTRINSIC SQRT
  REAL(dp), DIMENSION(nfull) :: arg1
  REAL(dp), DIMENSION(nbdirs, nfull) :: arg1d
  REAL(dp), DIMENSION(nfull) :: result1
  REAL(dp), DIMENSION(nbdirs, nfull) :: result1d
  INTEGER :: nd
  INTEGER :: nbdirs
  pi = 3.1415926_dp
  g = 9.81_dp
  DO nd=1,nbdirs
!add load from gravity of extra mass
    fz_w_gd(nd) = fzd(nd) - g*md(nd)
!add moment from gravity of extra mass
    myy_w_gd(nd) = myyd(nd) + g*mrhox*md(nd)
    f_xd(nd, :) = 0.0
    f_xd(nd, nfull) = -fxd(nd)
    f_yd(nd, :) = 0.0
    f_yd(nd, nfull) = -fyd(nd)
    f_zd(nd, :) = 0.0
    f_zd(nd, nfull) = fz_w_gd(nd)
    mxd(nd, :) = 0.0
    mxd(nd, nfull) = mxxd(nd)
    myd(nd, :) = 0.0
    myd(nd, nfull) = myy_w_gd(nd)
  END DO
  fz_w_g = fz - m*g
  myy_w_g = myy + m*g*mrhox
  massabove = 0.0_dp
  f_x(nfull) = -fx
  f_y(nfull) = -fy
  f_z(nfull) = fz_w_g
  mx(nfull) = mxx
  my(nfull) = myy_w_g
  DO nd=1,nbdirs
    massaboved(nd) = 0.0
  END DO
  DO i=nfull-1,1,-1
    fxtop = f_x(i+1)
    qx_top = qx(i+1)
    qx_bot = qx(i)
    qy_top = qy(i+1)
    qy_bot = qy(i)
    z_top = z_full(i+1)
    z_bot = z_full(i)
    qxload = qx_bot*(z_top-z_bot) + (qx_top-qx_bot)/(z_top-z_bot)*(&
&     0.5_dp*(z_top**2_dp-z_bot**2_dp)-z_bot*(z_top-z_bot))
    qyload = qy_bot*(z_top-z_bot) + (qy_top-qy_bot)/(z_top-z_bot)*(&
&     0.5_dp*(z_top**2_dp-z_bot**2_dp)-z_bot*(z_top-z_bot))
    q_x = (qx_top-qx_bot)/(z_top-z_bot)
    q_y = (qy_top-qy_bot)/(z_top-z_bot)
    f_x(i) = f_x(i+1) - qxload
    f_y(i) = f_y(i+1) - qyload
    area = (d_full(i+1)+d_full(i))/2._dp*pi*(t_full(i+1)+t_full(i))/&
&     2._dp
    DO nd=1,nbdirs
      qx_topd(nd) = qxd(nd, i+1)
      qx_botd(nd) = qxd(nd, i)
      qy_topd(nd) = qyd(nd, i+1)
      qy_botd(nd) = qyd(nd, i)
      z_topd(nd) = z_fulld(nd, i+1)
      z_botd(nd) = z_fulld(nd, i)
      qxloadd(nd) = qx_botd(nd)*(z_top-z_bot) + qx_bot*(z_topd(nd)-&
&       z_botd(nd)) + ((qx_topd(nd)-qx_botd(nd))*(z_top-z_bot)-(qx_top-&
&       qx_bot)*(z_topd(nd)-z_botd(nd)))*(0.5_dp*(z_top**2_dp-z_bot**&
&       2_dp)-z_bot*(z_top-z_bot))/(z_top-z_bot)**2 + (qx_top-qx_bot)*(&
&       0.5_dp*(2_dp*z_top*z_topd(nd)-2_dp*z_bot*z_botd(nd))-z_botd(nd)*&
&       (z_top-z_bot)-z_bot*(z_topd(nd)-z_botd(nd)))/(z_top-z_bot)
      qyloadd(nd) = qy_botd(nd)*(z_top-z_bot) + qy_bot*(z_topd(nd)-&
&       z_botd(nd)) + ((qy_topd(nd)-qy_botd(nd))*(z_top-z_bot)-(qy_top-&
&       qy_bot)*(z_topd(nd)-z_botd(nd)))*(0.5_dp*(z_top**2_dp-z_bot**&
&       2_dp)-z_bot*(z_top-z_bot))/(z_top-z_bot)**2 + (qy_top-qy_bot)*(&
&       0.5_dp*(2_dp*z_top*z_topd(nd)-2_dp*z_bot*z_botd(nd))-z_botd(nd)*&
&       (z_top-z_bot)-z_bot*(z_topd(nd)-z_botd(nd)))/(z_top-z_bot)
      q_xd(nd) = ((qx_topd(nd)-qx_botd(nd))*(z_top-z_bot)-(qx_top-qx_bot&
&       )*(z_topd(nd)-z_botd(nd)))/(z_top-z_bot)**2
      q_yd(nd) = ((qy_topd(nd)-qy_botd(nd))*(z_top-z_bot)-(qy_top-qy_bot&
&       )*(z_topd(nd)-z_botd(nd)))/(z_top-z_bot)**2
      qxmomd(nd) = q_yd(nd)*(z_top**3_dp-z_bot**3_dp)/3._dp + q_y*(3_dp*&
&       z_top**2.0*z_topd(nd)-3_dp*z_bot**2.0*z_botd(nd))/3._dp + 0.5_dp&
&       *((qy_botd(nd)-2._dp*(q_yd(nd)*z_bot+q_y*z_botd(nd)))*(z_top**&
&       2_dp-z_bot**2_dp)+(qy_bot-2._dp*q_y*z_bot)*(2_dp*z_top*z_topd(nd&
&       )-2_dp*z_bot*z_botd(nd))) + (q_yd(nd)*z_bot**2_dp+q_y*2_dp*z_bot&
&       *z_botd(nd)-qy_botd(nd)*z_bot-qy_bot*z_botd(nd))*(z_top-z_bot) +&
&       (q_y*z_bot**2_dp-qy_bot*z_bot)*(z_topd(nd)-z_botd(nd))
      qymomd(nd) = q_xd(nd)*(z_top**3_dp-z_bot**3_dp)/3._dp + q_x*(3_dp*&
&       z_top**2.0*z_topd(nd)-3_dp*z_bot**2.0*z_botd(nd))/3._dp + 0.5_dp&
&       *((qx_botd(nd)-2._dp*(q_xd(nd)*z_bot+q_x*z_botd(nd)))*(z_top**&
&       2_dp-z_bot**2_dp)+(qx_bot-2._dp*q_x*z_bot)*(2_dp*z_top*z_topd(nd&
&       )-2_dp*z_bot*z_botd(nd))) + (q_xd(nd)*z_bot**2_dp+q_x*2_dp*z_bot&
&       *z_botd(nd)-qx_botd(nd)*z_bot-qx_bot*z_botd(nd))*(z_top-z_bot) +&
&       (q_x*z_bot**2_dp-qx_bot*z_bot)*(z_topd(nd)-z_botd(nd))
      f_xd(nd, i) = f_xd(nd, i+1) - qxloadd(nd)
      f_yd(nd, i) = f_yd(nd, i+1) - qyloadd(nd)
      mxd(nd, i) = mxd(nd, i+1) + qxmomd(nd) - f_yd(nd, i+1)*(z_top-&
&       z_bot) - f_y(i+1)*(z_topd(nd)-z_botd(nd))
      myd(nd, i) = myd(nd, i+1) + qymomd(nd) - f_xd(nd, i+1)*(z_top-&
&       z_bot) - f_x(i+1)*(z_topd(nd)-z_botd(nd))
!Extra force from mass of tower
      aread(nd) = pi*((d_fulld(nd, i+1)+d_fulld(nd, i))*(t_full(i+1)+&
&       t_full(i))/2._dp+(d_full(i+1)+d_full(i))*(t_fulld(nd, i+1)+&
&       t_fulld(nd, i))/2._dp)/2._dp
      volumed(nd) = aread(nd)*(z_full(i+1)-z_full(i)) + area*(z_fulld(nd&
&       , i+1)-z_fulld(nd, i))
      sectionmassd(nd) = rho(i)*volumed(nd)
      massaboved(nd) = massaboved(nd) + sectionmassd(nd)
      f_zd(nd, i) = fz_w_gd(nd) - g*massaboved(nd)
    END DO
    qxmom = q_y*1._dp/3._dp*(z_top**3_dp-z_bot**3_dp) + (qy_bot-2._dp*&
&     q_y*z_bot)*0.5_dp*(z_top**2_dp-z_bot**2_dp) + (q_y*z_bot**2_dp-&
&     qy_bot*z_bot)*(z_top-z_bot)
    qymom = q_x*1._dp/3._dp*(z_top**3_dp-z_bot**3_dp) + (qx_bot-2._dp*&
&     q_x*z_bot)*0.5_dp*(z_top**2_dp-z_bot**2_dp) + (q_x*z_bot**2_dp-&
&     qx_bot*z_bot)*(z_top-z_bot)
    mx(i) = mx(i+1) + qxmom - f_y(i+1)*(z_top-z_bot)
    my(i) = my(i+1) + qymom - f_x(i+1)*(z_top-z_bot)
    volume = area*(z_full(i+1)-z_full(i))
    sectionmass = volume*rho(i)
    massabove = massabove + sectionmass
    f_z(i) = fz_w_g - massabove*g
  END DO
  az = pi*d_full*t_full
  iyy = pi*(d_full/2._dp)**3_dp*t_full
  arg1(:) = mx**2_dp + my**2_dp
  result1 = SQRT(arg1(:))
  DO nd=1,nbdirs
    azd(nd, :) = pi*(d_fulld(nd, :)*t_full+d_full*t_fulld(nd, :))
    iyyd(nd, :) = pi*(3_dp*(d_full/2._dp)**2.0*d_fulld(nd, :)*t_full/&
&     2._dp+(d_full/2._dp)**3_dp*t_fulld(nd, :))
    arg1d(nd, :) = 2_dp*mx*mxd(nd, :) + 2_dp*my*myd(nd, :)
    WHERE (arg1(:) .EQ. 0.0)
      result1d(nd, :) = 0.0
    ELSEWHERE
      result1d(nd, :) = arg1d(nd, :)/(2.0*SQRT(arg1(:)))
    END WHERE
    axial_stressd(nd, :) = (f_zd(nd, :)*az-f_z*azd(nd, :))/az**2 - ((&
&     result1d(nd, :)*iyy-result1*iyyd(nd, :))*d_full/iyy**2+result1*&
&     d_fulld(nd, :)/iyy)/2.0_dp
    arg1d(nd, :) = 2_dp*f_x*f_xd(nd, :) + 2_dp*f_y*f_yd(nd, :)
  END DO
  axial_stress = f_z/az - result1/iyy*d_full/2.0_dp
  arg1(:) = f_x**2_dp + f_y**2_dp
  result1 = SQRT(arg1(:))
  DO nd=1,nbdirs
    WHERE (arg1(:) .EQ. 0.0)
      result1d(nd, :) = 0.0
    ELSEWHERE
      result1d(nd, :) = arg1d(nd, :)/(2.0*SQRT(arg1(:)))
    END WHERE
    shear_stressd(nd, :) = (2._dp*result1d(nd, :)*az-2._dp*result1*azd(&
&     nd, :))/az**2
  END DO
  shear_stress = 2._dp*result1/az
END SUBROUTINE AXIAL_AND_SHEAR_DV
